using System.Text.Json;

namespace SheetMapper.Windows;

public sealed class MainForm : Form
{
    readonly Button sourceButton = new() { Text = "选择基础数据表", AutoSize = true };
    readonly Button templateButton = new() { Text = "选择输出模板", AutoSize = true };
    readonly ComboBox sourceSheets = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 210 };
    readonly ComboBox templateSheets = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 210 };
    readonly NumericUpDown headerRow = new() { Minimum = 1, Maximum = 10000, Value = 1, Width = 60 };
    readonly NumericUpDown dataRow = new() { Minimum = 1, Maximum = 10000, Value = 2, Width = 60 };
    readonly DataGridView sourceGrid = Grid(), templateGrid = Grid();
    readonly Label selectedSource = new() { Text = "左侧字段", TextAlign = ContentAlignment.MiddleCenter, Dock = DockStyle.Fill };
    readonly Label selectedTarget = new() { Text = "右侧单元格", TextAlign = ContentAlignment.MiddleCenter, Dock = DockStyle.Fill };
    readonly Button addMapping = new() { Text = "建立映射", Dock = DockStyle.Fill, Height = 42 };
    readonly DataGridView mappingGrid = new() { Dock = DockStyle.Fill, AllowUserToAddRows = false, AutoGenerateColumns = false, RowHeadersVisible = false };
    readonly ComboBox keyField = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 180 };
    readonly ComboBox outputMode = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 200 };
    readonly NumericUpDown sheetsPerBook = new() { Minimum = 1, Maximum = 200, Value = 20, Width = 60 };
    readonly Button exportConfig = new() { Text = "导出配置" }, importConfig = new() { Text = "导入配置" }, saveMemory = new() { Text = "记住当前映射" }, deleteMemory = new() { Text = "删除常用映射" }, generate = new() { Text = "按映射关系批量生成", AutoSize = true }, cancel = new() { Text = "取消", Enabled = false };
    readonly TextBox memoryName = new() { PlaceholderText = "常用映射名称", Width = 150 }; readonly ComboBox memoriesBox = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 180 };
    readonly ComboBox language = new() { DropDownStyle = ComboBoxStyle.DropDownList, Width = 120 };
    readonly ProgressBar progress = new() { Width = 220 }; readonly Label status = new() { AutoSize = true, Text = "请选择基础数据表和输出模板" };
    readonly List<FieldMapping> mappings = []; readonly List<MappingMemory> memories = [];
    CancellationTokenSource? generationCancellation;
    WorkbookIndex? sourceIndex, templateIndex; SheetData? sourceData, templateData; string selectedField = "", selectedCell = "";

    public MainForm()
    {
        Text = "SheetMapper - 通用表格映射批量生成工具"; Width = 1500; Height = 900; MinimumSize = new(1100, 700); StartPosition = FormStartPosition.CenterScreen;
        Font = new("Microsoft YaHei UI", 10); BackColor = Color.FromArgb(242, 247, 251);
        language.DataSource = new[] { "简体中文", "English" }; language.SelectedIndex = Properties.SettingsLanguage == "en" ? 1 : 0;
        outputMode.DataSource = new[] { "一个工作簿包含多个Sheet", "每行一个Excel文件" };
        mappingGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "基础字段", DataPropertyName = "Source", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
        mappingGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "模板单元格", DataPropertyName = "Target", Width = 130 });
        mappingGrid.Columns.Add(new DataGridViewComboBoxColumn { HeaderText = "数据处理", DataPropertyName = "Transform", DataSource = Enum.GetValues<ValueTransform>(), Width = 120 });
        mappingGrid.Columns.Add(new DataGridViewCheckBoxColumn { HeaderText = "必填", DataPropertyName = "Required", Width = 60 });
        mappingGrid.Columns.Add(new DataGridViewButtonColumn { HeaderText = "操作", Text = "删除", UseColumnTextForButtonValue = true, Width = 70 });

        var root = new TableLayoutPanel { Dock = DockStyle.Fill, RowCount = 5, ColumnCount = 1, Padding = new(16) };
        root.RowStyles.Add(new(SizeType.Absolute, 68)); root.RowStyles.Add(new(SizeType.Absolute, 58)); root.RowStyles.Add(new(SizeType.Percent, 58)); root.RowStyles.Add(new(SizeType.Percent, 42)); root.RowStyles.Add(new(SizeType.Absolute, 58));
        root.Controls.Add(Header(), 0, 0); root.Controls.Add(Setup(), 0, 1); root.Controls.Add(PreviewArea(), 0, 2); root.Controls.Add(MappingArea(), 0, 3); root.Controls.Add(Footer(), 0, 4); Controls.Add(root);
        LoadMemories(); ApplyLanguage(); language.SelectedIndexChanged += (_, _) => { Properties.SettingsLanguage = language.SelectedIndex == 1 ? "en" : "zh"; ApplyLanguage(); };
        sourceButton.Click += (_, _) => ChooseWorkbook(true); templateButton.Click += (_, _) => ChooseWorkbook(false);
        sourceSheets.SelectedIndexChanged += async (_, _) => await LoadSheet(true); templateSheets.SelectedIndexChanged += async (_, _) => await LoadSheet(false);
        sourceGrid.CellClick += SourceCell; templateGrid.CellClick += TemplateCell; addMapping.Click += (_, _) => AddMapping(); mappingGrid.CellContentClick += DeleteMapping;
        exportConfig.Click += (_, _) => ExportConfig(); importConfig.Click += (_, _) => ImportConfig(); saveMemory.Click += (_, _) => SaveMemory(); deleteMemory.Click += (_, _) => DeleteMemory(); memoriesBox.SelectedIndexChanged += (_, _) => ApplyMemory(); generate.Click += async (_, _) => await Generate(); cancel.Click += (_, _) => generationCancellation?.Cancel();
    }

    Control Header() { var p = new Panel { Dock = DockStyle.Fill, BackColor = Color.FromArgb(21, 79, 119) }; p.Controls.Add(new Label { Name = "HeaderTitle", Text = "SheetMapper\nWindows 10+ 绿色便携版 · 文件仅在本机处理", ForeColor = Color.White, Font = new(Font.FontFamily, 15, FontStyle.Bold), AutoSize = true, Location = new(18, 10) }); language.Location = new(1310, 18); language.Anchor = AnchorStyles.Top | AnchorStyles.Right; p.Controls.Add(language); return p; }
    Control Setup() { var p = new FlowLayoutPanel { Dock = DockStyle.Fill, Padding = new(8), WrapContents = false }; p.Controls.AddRange([sourceButton, new Label { Text = "工作表", AutoSize = true, Padding = new(8) }, sourceSheets, new Label { Text = "表头行", AutoSize = true, Padding = new(8) }, headerRow, new Label { Text = "数据起始行", AutoSize = true, Padding = new(8) }, dataRow, templateButton, new Label { Text = "模板工作表", AutoSize = true, Padding = new(8) }, templateSheets]); return p; }
    Control PreviewArea() { var split = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 3 }; split.ColumnStyles.Add(new(SizeType.Percent, 45)); split.ColumnStyles.Add(new(SizeType.Absolute, 210)); split.ColumnStyles.Add(new(SizeType.Percent, 55)); split.Controls.Add(Group("基础数据表预览（支持拖入文件）", sourceGrid, true), 0, 0); var controls = new TableLayoutPanel { Dock = DockStyle.Fill, RowCount = 6, Padding = new(12) }; controls.RowStyles.Add(new(SizeType.Absolute, 48)); controls.RowStyles.Add(new(SizeType.Absolute, 48)); controls.RowStyles.Add(new(SizeType.Absolute, 34)); controls.RowStyles.Add(new(SizeType.Absolute, 48)); controls.RowStyles.Add(new(SizeType.Absolute, 48)); controls.RowStyles.Add(new(SizeType.Percent, 100)); controls.Controls.Add(new Label { Text = "建立映射", Font = new(Font.FontFamily, 14, FontStyle.Bold), TextAlign = ContentAlignment.MiddleCenter, Dock = DockStyle.Fill }, 0, 0); controls.Controls.Add(selectedSource, 0, 1); controls.Controls.Add(new Label { Text = "↓", TextAlign = ContentAlignment.MiddleCenter, Dock = DockStyle.Fill }, 0, 2); controls.Controls.Add(selectedTarget, 0, 3); controls.Controls.Add(addMapping, 0, 4); split.Controls.Add(controls, 1, 0); split.Controls.Add(Group("输出模板预览（支持拖入文件）", templateGrid, false), 2, 0); return split; }
    Control Group(string title, Control content, bool source) { var box = new GroupBox { Text = title, Dock = DockStyle.Fill, Padding = new(8), AllowDrop = true }; box.Controls.Add(content); box.DragEnter += (_, e) => { if (e.Data?.GetDataPresent(DataFormats.FileDrop) == true) e.Effect = DragDropEffects.Copy; }; box.DragDrop += (_, e) => { var f = (e.Data?.GetData(DataFormats.FileDrop) as string[])?.FirstOrDefault(); if (f != null) OpenWorkbook(f, source); }; return box; }
    Control MappingArea() { var p = new TableLayoutPanel { Dock = DockStyle.Fill, RowCount = 2 }; p.RowStyles.Add(new(SizeType.Absolute, 42)); p.RowStyles.Add(new(SizeType.Percent, 100)); var bar = new FlowLayoutPanel { Dock = DockStyle.Fill }; bar.Controls.AddRange([new Label { Text = "已确定的映射关系", Font = new(Font.FontFamily, 11, FontStyle.Bold), AutoSize = true, Padding = new(5) }, exportConfig, importConfig, memoryName, saveMemory, memoriesBox, deleteMemory]); p.Controls.Add(bar, 0, 0); p.Controls.Add(mappingGrid, 0, 1); return p; }
    Control Footer() { var p = new FlowLayoutPanel { Dock = DockStyle.Fill, Padding = new(4), WrapContents = false }; p.Controls.AddRange([status, new Label { Text = "   主键", AutoSize = true, Padding = new(6) }, keyField, new Label { Text = "输出方式", AutoSize = true, Padding = new(6) }, outputMode, new Label { Text = "每工作簿 Sheet 数", AutoSize = true, Padding = new(6) }, sheetsPerBook, progress, cancel, generate]); return p; }

    static DataGridView Grid() => new() { Dock = DockStyle.Fill, ReadOnly = true, AllowUserToAddRows = false, AllowUserToDeleteRows = false, RowHeadersWidth = 55, AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells, SelectionMode = DataGridViewSelectionMode.CellSelect, BackgroundColor = Color.White };
    void ChooseWorkbook(bool source) { using var d = new OpenFileDialog { Filter = "Excel 工作簿 (*.xlsx)|*.xlsx|WPS/Excel 旧格式 (*.et;*.ett;*.xls)|*.et;*.ett;*.xls", Title = source ? "选择基础数据表" : "选择输出模板" }; if (d.ShowDialog() == DialogResult.OK) OpenWorkbook(d.FileName, source); }
    void OpenWorkbook(string file, bool source) { try { if (!Path.GetExtension(file).Equals(".xlsx", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("请先在 WPS 中另存为 .xlsx 后再导入"); var index = XlsxReader.Index(file); if (source) { sourceIndex = index; sourceSheets.DataSource = index.Sheets.ToList(); sourceSheets.DisplayMember = "Name"; } else { templateIndex = index; templateSheets.DataSource = index.Sheets.ToList(); templateSheets.DisplayMember = "Name"; } status.Text = $"已读取：{Path.GetFileName(file)}"; } catch (Exception ex) { Error(ex); } }
    async Task LoadSheet(bool source) { try { var index = source ? sourceIndex : templateIndex; var combo = source ? sourceSheets : templateSheets; if (index == null || combo.SelectedItem is not SheetInfo info) return; status.Text = "正在读取工作表……"; var data = await Task.Run(() => XlsxReader.Read(index, info, 50, 200)); if (source) { sourceData = data; Fill(sourceGrid, data); RefreshHeaders(); } else { templateData = data; Fill(templateGrid, data); } status.Text = $"已读取工作表：{info.Name}"; } catch (Exception ex) { Error(ex); } }
    static void Fill(DataGridView grid, SheetData data) { grid.Columns.Clear(); grid.Rows.Clear(); var cols = data.Rows.Max(r => r.Count); for (var c = 0; c < cols; c++) grid.Columns.Add($"c{c}", XlsxReader.ColumnName(c)); foreach (var row in data.Rows) grid.Rows.Add(Enumerable.Range(0, cols).Select(c => c < row.Count ? row[c] : "").ToArray()); for (var r = 0; r < grid.Rows.Count; r++) grid.Rows[r].HeaderCell.Value = (r + 1).ToString(); }
    void RefreshHeaders() { if (sourceData == null || headerRow.Value > sourceData.Rows.Count) return; var fields = sourceData.Rows[(int)headerRow.Value - 1].Where(x => !string.IsNullOrWhiteSpace(x)).Distinct().ToArray(); keyField.DataSource = fields; AutoApplyMemory(fields); }
    void SourceCell(object? s, DataGridViewCellEventArgs e) { if (sourceData == null || e.ColumnIndex < 0 || headerRow.Value > sourceData.Rows.Count) return; var row = sourceData.Rows[(int)headerRow.Value - 1]; selectedField = e.ColumnIndex < row.Count ? row[e.ColumnIndex].Trim() : ""; selectedSource.Text = selectedField.Length > 0 ? selectedField : "空白表头不可选"; }
    void TemplateCell(object? s, DataGridViewCellEventArgs e) { if (e.RowIndex < 0 || e.ColumnIndex < 0) return; selectedCell = $"{XlsxReader.ColumnName(e.ColumnIndex)}{e.RowIndex + 1}"; selectedTarget.Text = selectedCell; }
    void AddMapping() { if (selectedField.Length == 0 || selectedCell.Length == 0) return; mappings.RemoveAll(x => x.Target.Equals(selectedCell, StringComparison.OrdinalIgnoreCase)); mappings.Add(new() { Source = selectedField, Target = selectedCell }); RefreshMappings(); }
    void RefreshMappings() { mappingGrid.DataSource = null; mappingGrid.DataSource = mappings.ToList(); }
    void DeleteMapping(object? s, DataGridViewCellEventArgs e) { if (e.RowIndex >= 0 && e.ColumnIndex == mappingGrid.Columns.Count - 1) { mappings.RemoveAt(e.RowIndex); RefreshMappings(); } }
    MappingConfiguration CurrentConfig() => new() { HeaderRow = (int)headerRow.Value, DataStartRow = (int)dataRow.Value, KeyField = keyField.Text, SheetsPerWorkbook = (int)sheetsPerBook.Value, OutputMode = outputMode.SelectedIndex == 1 ? OutputMode.Separate : OutputMode.Combined, Mappings = mappings.ToList() };
    void ExportConfig() { using var d = new SaveFileDialog { Filter = "JSON 配置|*.json", FileName = "SheetMapper映射配置.json" }; if (d.ShowDialog() == DialogResult.OK) File.WriteAllText(d.FileName, JsonSerializer.Serialize(CurrentConfig(), JsonOptions)); }
    void ImportConfig() { using var d = new OpenFileDialog { Filter = "JSON 配置|*.json" }; if (d.ShowDialog() != DialogResult.OK) return; try { var c = JsonSerializer.Deserialize<MappingConfiguration>(File.ReadAllText(d.FileName), JsonOptions) ?? throw new InvalidDataException(); headerRow.Value = c.HeaderRow; dataRow.Value = c.DataStartRow; sheetsPerBook.Value = c.SheetsPerWorkbook; outputMode.SelectedIndex = c.OutputMode == OutputMode.Separate ? 1 : 0; mappings.Clear(); mappings.AddRange(c.Mappings); RefreshHeaders(); keyField.SelectedItem = c.KeyField; RefreshMappings(); } catch (Exception ex) { Error(ex); } }
    async Task Generate() { if (sourceIndex == null || templateIndex == null || sourceSheets.SelectedItem is not SheetInfo ss || templateSheets.SelectedItem is not SheetInfo ts) return; using var d = new SaveFileDialog { Filter = "ZIP 压缩包|*.zip", FileName = "SheetMapper生成结果.zip" }; if (d.ShowDialog() != DialogResult.OK) return; try { generate.Enabled = false; cancel.Enabled = true; generationCancellation = new(); var report = new Progress<(string Stage, int Current, int Total)>(x => { status.Text = $"{x.Stage} {x.Current}/{x.Total}"; progress.Maximum = Math.Max(1, x.Total); progress.Value = Math.Min(progress.Maximum, x.Current); }); var result = await XlsxGenerator.GenerateAsync(sourceIndex, ss, templateIndex.FilePath, ts, CurrentConfig(), d.FileName, report, generationCancellation.Token); status.Text = $"完成：成功 {result.Success}，异常 {result.Errors}，共 {result.Batches} 批"; MessageBox.Show($"生成完成\n成功：{result.Success}\n异常：{result.Errors}\n输出：{result.Output}", "SheetMapper", MessageBoxButtons.OK, MessageBoxIcon.Information); } catch (OperationCanceledException) { status.Text = "生成已取消"; } catch (Exception ex) { Error(ex); } finally { generationCancellation?.Dispose(); generationCancellation = null; generate.Enabled = true; cancel.Enabled = false; } }
    string MemoryFile => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "SheetMapper", "mapping-memories.json");
    void LoadMemories() { try { if (File.Exists(MemoryFile)) memories.AddRange(JsonSerializer.Deserialize<List<MappingMemory>>(File.ReadAllText(MemoryFile), JsonOptions) ?? []); RefreshMemoryBox(); } catch { } }
    void PersistMemories() { Directory.CreateDirectory(Path.GetDirectoryName(MemoryFile)!); File.WriteAllText(MemoryFile, JsonSerializer.Serialize(memories.Take(50), JsonOptions)); RefreshMemoryBox(); }
    void RefreshMemoryBox() { var selected = memoriesBox.Text; memoriesBox.DataSource = null; memoriesBox.DataSource = memories.ToList(); memoriesBox.DisplayMember = "Name"; if (memories.Count == 0) memoriesBox.Text = ""; else if (memories.Any(x => x.Name == selected)) memoriesBox.Text = selected; }
    void SaveMemory() { if (mappings.Count == 0 || sourceData == null || templateData == null) return; var name = string.IsNullOrWhiteSpace(memoryName.Text) ? $"常用映射{memories.Count + 1}" : memoryName.Text.Trim(); memories.RemoveAll(x => x.Name == name); memories.Insert(0, new MappingMemory { Name = name, SourceFields = sourceData.Rows[(int)headerRow.Value - 1].Where(x => !string.IsNullOrWhiteSpace(x)).Select(Normalize).ToList(), TemplateLabels = TemplateLabels(), Mappings = mappings.Select(Clone).ToList(), SheetsPerWorkbook = (int)sheetsPerBook.Value, OutputMode = outputMode.SelectedIndex == 1 ? OutputMode.Separate : OutputMode.Combined }); PersistMemories(); memoriesBox.SelectedIndex = 0; status.Text = $"已记住常用映射：{name}"; }
    void DeleteMemory() { if (memoriesBox.SelectedItem is not MappingMemory memory) return; memories.RemoveAll(x => x.Id == memory.Id); PersistMemories(); status.Text = $"已删除常用映射：{memory.Name}"; }
    void ApplyMemory() { if (memoriesBox.SelectedItem is not MappingMemory memory || sourceData == null || templateData == null) return; var actual = sourceData.Rows[(int)headerRow.Value - 1].Where(x => !string.IsNullOrWhiteSpace(x)).ToDictionary(Normalize, x => x); var sourceScore = memory.SourceFields.Count == 0 ? 0 : memory.SourceFields.Count(actual.ContainsKey) / (double)memory.SourceFields.Count; var labels = TemplateLabels().ToHashSet(); var templateScore = memory.TemplateLabels.Count == 0 ? 0 : memory.TemplateLabels.Count(labels.Contains) / (double)memory.TemplateLabels.Count; if (sourceScore < .6 || templateScore < .45) return; mappings.Clear(); mappings.AddRange(memory.Mappings.Where(x => actual.ContainsKey(Normalize(x.Source))).Select(x => { var c = Clone(x); c.Source = actual[Normalize(x.Source)]; return c; })); sheetsPerBook.Value = Math.Clamp(memory.SheetsPerWorkbook, 1, 200); outputMode.SelectedIndex = memory.OutputMode == OutputMode.Separate ? 1 : 0; memoryName.Text = memory.Name; RefreshMappings(); status.Text = $"已自动应用常用映射：{memory.Name}"; }
    void AutoApplyMemory(string[] fields) { if (templateData == null) return; var normalized = fields.Select(Normalize).ToHashSet(); var labels = TemplateLabels().ToHashSet(); var best = memories.Select(x => (Memory: x, Score: (x.SourceFields.Count == 0 ? 0 : x.SourceFields.Count(normalized.Contains) / (double)x.SourceFields.Count) + (x.TemplateLabels.Count == 0 ? 0 : x.TemplateLabels.Count(labels.Contains) / (double)x.TemplateLabels.Count))).OrderByDescending(x => x.Score).FirstOrDefault(); if (best.Memory != null && best.Score >= 1.05) { memoriesBox.SelectedItem = best.Memory; ApplyMemory(); } }
    List<string> TemplateLabels() { var result = new List<string>(); if (templateData == null) return result; for (var r = 0; r < Math.Min(60, templateData.Rows.Count); r++) for (var c = 0; c < Math.Min(40, templateData.Rows[r].Count); c++) if (!string.IsNullOrWhiteSpace(templateData.Rows[r][c]) && !double.TryParse(templateData.Rows[r][c], out _)) result.Add($"{XlsxReader.ColumnName(c)}{r + 1}:{Normalize(templateData.Rows[r][c])}"); return result.Distinct().ToList(); }
    static string Normalize(string x) => x.Replace("\u200B", "").Trim().Replace(" ", "").Replace('（', '(').Replace('）', ')').ToLowerInvariant();
    static FieldMapping Clone(FieldMapping x) => new() { Source = x.Source, Target = x.Target, Transform = x.Transform, Required = x.Required };
    void Error(Exception ex) { status.Text = ex.Message; MessageBox.Show(ex.Message, "SheetMapper", MessageBoxButtons.OK, MessageBoxIcon.Error); }
    void ApplyLanguage()
    {
        var en = Properties.SettingsLanguage == "en";
        sourceButton.Text = en ? "Choose Source Workbook" : "选择基础数据表"; templateButton.Text = en ? "Choose Output Template" : "选择输出模板";
        addMapping.Text = en ? "Add Mapping" : "建立映射"; exportConfig.Text = en ? "Export Configuration" : "导出配置"; importConfig.Text = en ? "Import Configuration" : "导入配置";
        saveMemory.Text = en ? "Save Preset" : "记住当前映射"; deleteMemory.Text = en ? "Delete Preset" : "删除常用映射"; cancel.Text = en ? "Cancel" : "取消"; generate.Text = en ? "Generate from Mappings" : "按映射关系批量生成";
        selectedSource.Text = en ? "Source Field" : "左侧字段"; selectedTarget.Text = en ? "Template Cell" : "右侧单元格"; memoryName.PlaceholderText = en ? "Preset name" : "常用映射名称";
        if (Controls.Find("HeaderTitle", true).FirstOrDefault() is Label title) title.Text = en ? "SheetMapper\nWindows 10+ portable · Files stay on this PC" : "SheetMapper\nWindows 10+ 绿色便携版 · 文件仅在本机处理";
        outputMode.DataSource = en ? new[] { "Multiple sheets per workbook", "One Excel file per row" } : new[] { "一个工作簿包含多个Sheet", "每行一个Excel文件" };
    }
    static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true, PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase, Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() } };
}

static class Properties
{
    static readonly string FilePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "SheetMapper", "language.txt");
    public static string SettingsLanguage
    {
        get { try { return File.Exists(FilePath) ? File.ReadAllText(FilePath).Trim() : "zh"; } catch { return "zh"; } }
        set { try { Directory.CreateDirectory(Path.GetDirectoryName(FilePath)!); File.WriteAllText(FilePath, value); } catch { } }
    }
}
